<?php

/**
 * LlmsTxtController.
 *
 * Serves the llms.txt AI-discovery manifest.
 *
 * @package    ArtisanPack_UI
 * @subpackage SEO
 *
 * @author     Jacob Martella <me@jacobmartella.com>
 *
 * @since      1.4.0
 */

declare( strict_types=1 );

namespace ArtisanPackUI\SEO\Http\Controllers;

use ArtisanPackUI\SEO\Services\SitemapService;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

/**
 * LlmsTxtController class.
 *
 * Emits the llms.txt manifest generated by SitemapService.
 *
 * @package    ArtisanPack_UI
 * @subpackage SEO
 *
 * @since      1.4.0
 */
class LlmsTxtController extends Controller
{
	/**
	 * Create a new LlmsTxtController instance.
	 *
	 * @since 1.4.0
	 *
	 * @param  SitemapService  $sitemapService  The sitemap service.
	 */
	public function __construct( protected SitemapService $sitemapService )
	{
	}

	/**
	 * Serve the llms.txt manifest.
	 *
	 * @since 1.4.0
	 *
	 * @return Response
	 */
	public function index(): Response
	{
		if ( true !== config( 'seo.llms_txt.enabled', true ) ) {
			return response( 'Not Found', 404 );
		}

		$content = $this->sitemapService->generateLlmsTxt();

		return response( $content, 200 )
			->header( 'Content-Type', 'text/plain; charset=UTF-8' )
			->header( 'Cache-Control', 'public, max-age=3600' );
	}
}
